version: "3.8"
services:
  apigateway:
    depends_on:
        - auth
    container_name: apigateway
    build:
      context: .
      args:
        - APP=apigateway
    restart: always
    ports:
      - 8000:3000
    networks:
      - app_network
    environment:
      - AUTH_GRPC_URL=auth:50001

  auth:
    container_name: auth
    build:
      context: .
      args:
        - APP=auth
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      - GRPC_URL=auth:50001

networks:
  app_network:
    driver: bridge
